### ISSUE TITLE
Error starting up openVPN server via docker

### ISSUE THREAD

**Issue by alirezastack** [linuxserver-archive/docker-openvpn-as#147]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
normal openVPN startup

## Current Behavior
It gives traceback error:

```
Traceback (most recent call last):
  File "/usr/local/openvpn_as/bin/_ovpn-init", line 557, in <module>
    OVPN_KEY_ALGORITHM, OVPN_KEY_SIZE = get_cert_algorithms("OpenVPN CA", DEFAULT_KEY_ALGORITHM, DEFAULT_KEY_SIZE)
  File "/usr/local/openvpn_as/bin/_ovpn-init", line 261, in get_cert_algorithms
    user_input = get_raw_input("> Press ENTER for default [ %d ]:" % DEFAULT_KEY_SIZE)
  File "/usr/local/openvpn_as/bin/_ovpn-init", line 78, in get_raw_input
    return input(prompt)
EOFError: EOF when reading a line
> Press ENTER for default [ 2048 ]:Stopping openvpn-as now; will start again later after configuring
cat: /var/run/openvpnas.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
[cont-init.d] 40-openvpn-init: exited 0.
[cont-init.d] 50-interface: executing...
MOD Default {'admin_ui.https.ip_address': None} {'admin_ui.https.ip_address': 'eth0'}
MOD Default {'cs.https.ip_address': None} {'cs.https.ip_address': 'eth0'}
MOD Default {'vpn.daemon.0.listen.ip_address': None} {'vpn.daemon.0.listen.ip_address': 'eth0'}
MOD Default {'vpn.daemon.0.server.ip_address': None} {'vpn.daemon.0.server.ip_address': 'eth0'}
[cont-init.d] 50-interface: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

## Steps to Reproduce
1. mkdir ~/openvpn-as
2. docker run -d   --name=openvpn-as   --cap-add=NET_ADMIN   -e PUID=1000   -e PGID=1000   -e TZ=Europe/Lisbon   -p 943:943   -p 9443:9443   -p 1194:1194/udp   -v $PWD/openvpn-as:/config   --restart unless-stopped   ghcr.io/linuxserver/openvpn-as
3. docker logs -f --tail 10 openvpn-as

## Environment
**OS: Ubuntu 20.04.2 LTS (Focal Fossa)
**CPU architecture:** x86_64
**How docker service was installed:** from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)
explained in **Steps to Reproduce**

## Docker logs

```
root@Server-OpenVPN:~# docker logs openvpn-as
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-time: executing...

Current default time zone: 'Europe/Lisbon'
Local time is now:      Tue Jun 15 12:24:27 WEST 2021.
Universal Time is now:  Tue Jun 15 11:24:27 UTC 2021.

[cont-init.d] 20-time: exited 0.
[cont-init.d] 30-config: executing...
installing openvpn-as for the first time
Get:1 http://as-repository.openvpn.net/as/debian bionic InRelease [3,186 B]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:5 http://as-repository.openvpn.net/as/debian bionic/main amd64 Packages [6,008 B]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main Sources [642 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2,619 kB]
Fetched 3,448 kB in 1s (2,705 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libmariadb3 libmpdec2 libpython3-stdlib libpython3.6-minimal
  libpython3.6-stdlib openvpn-as-bundled-clients python3 python3-decorator
  python3-ldap3 python3-migrate python3-minimal python3-mysqldb python3-pbr
  python3-pkg-resources python3-pyasn1 python3-six python3-sqlalchemy
  python3-sqlparse python3-tempita python3.6 python3.6-minimal
Suggested packages:
  python3-doc python3-tk python3-venv python-migrate-doc default-mysql-server
  | virtual-mysql-server python-egenix-mxdatetime python3-mysqldb-dbg
  python3-setuptools python-sqlalchemy-doc python3-psycopg2 python3-pymysql
  python3-fdb python-sqlparse-doc python3.6-venv python3.6-doc binutils
  binfmt-support
The following NEW packages will be installed:
  libmariadb3 libmpdec2 libpython3-stdlib libpython3.6-minimal
  libpython3.6-stdlib openvpn-as openvpn-as-bundled-clients python3
  python3-decorator python3-ldap3 python3-migrate python3-minimal
  python3-mysqldb python3-pbr python3-pkg-resources python3-pyasn1 python3-six
  python3-sqlalchemy python3-sqlparse python3-tempita python3.6
  python3.6-minimal
0 upgraded, 22 newly installed, 0 to remove and 0 not upgraded.
Need to get 144 MB of archives.
After this operation, 201 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpython3.6-minimal amd64 3.6.9-1~18.04ubuntu1.4 [534 kB]
Get:2 http://as-repository.openvpn.net/as/debian bionic/main amd64 openvpn-as-bundled-clients all 16 [123 MB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3.6-minimal amd64 3.6.9-1~18.04ubuntu1.4 [1,610 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3-minimal amd64 3.6.7-1~18.04 [23.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 libmpdec2 amd64 2.4.2-1ubuntu1 [84.1 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpython3.6-stdlib amd64 3.6.9-1~18.04ubuntu1.4 [1,712 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3.6 amd64 3.6.9-1~18.04ubuntu1.4 [203 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpython3-stdlib amd64 3.6.7-1~18.04 [7,240 B]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3 amd64 3.6.7-1~18.04 [47.2 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libmariadb3 amd64 3.0.3-1build1 [106 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/main amd64 python3-pkg-resources all 39.0.1-2 [98.8 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/universe amd64 python3-decorator all 4.1.2-1 [9,364 B]
Get:13 http://archive.ubuntu.com/ubuntu bionic/main amd64 python3-six all 1.11.0-2 [11.4 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic/main amd64 python3-pbr all 3.1.1-3ubuntu3 [53.8 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/main amd64 python3-sqlalchemy all 1.1.11+ds1-1ubuntu1 [680 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic/main amd64 python3-sqlparse all 0.2.4-0.1 [28.1 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic/main amd64 python3-tempita all 0.5.2-2 [13.9 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic/universe amd64 python3-migrate all 0.11.0-2 [69.4 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic/main amd64 python3-mysqldb amd64 1.3.10-1build1 [46.0 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic/main amd64 python3-pyasn1 all 0.4.2-3 [46.8 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic/universe amd64 python3-ldap3 all 2.4.1-1 [217 kB]
Get:22 http://as-repository.openvpn.net/as/debian bionic/main amd64 openvpn-as amd64 2.9.0-5c5bd120-Ubuntu18 [15.5 MB]
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 22.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 22.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Fetched 144 MB in 2s (61.5 MB/s)
Selecting previously unselected package libpython3.6-minimal:amd64.
(Reading database ... 13217 files and directories currently installed.)
Preparing to unpack .../libpython3.6-minimal_3.6.9-1~18.04ubuntu1.4_amd64.deb ...
Unpacking libpython3.6-minimal:amd64 (3.6.9-1~18.04ubuntu1.4) ...
Selecting previously unselected package python3.6-minimal.
Preparing to unpack .../python3.6-minimal_3.6.9-1~18.04ubuntu1.4_amd64.deb ...
Unpacking python3.6-minimal (3.6.9-1~18.04ubuntu1.4) ...
Setting up libpython3.6-minimal:amd64 (3.6.9-1~18.04ubuntu1.4) ...
Setting up python3.6-minimal (3.6.9-1~18.04ubuntu1.4) ...
Selecting previously unselected package python3-minimal.
(Reading database ... 13455 files and directories currently installed.)
Preparing to unpack .../python3-minimal_3.6.7-1~18.04_amd64.deb ...
Unpacking python3-minimal (3.6.7-1~18.04) ...
Selecting previously unselected package libmpdec2:amd64.
Preparing to unpack .../libmpdec2_2.4.2-1ubuntu1_amd64.deb ...
Unpacking libmpdec2:amd64 (2.4.2-1ubuntu1) ...
Selecting previously unselected package libpython3.6-stdlib:amd64.
Preparing to unpack .../libpython3.6-stdlib_3.6.9-1~18.04ubuntu1.4_amd64.deb ...
Unpacking libpython3.6-stdlib:amd64 (3.6.9-1~18.04ubuntu1.4) ...
Selecting previously unselected package python3.6.
Preparing to unpack .../python3.6_3.6.9-1~18.04ubuntu1.4_amd64.deb ...
Unpacking python3.6 (3.6.9-1~18.04ubuntu1.4) ...
Selecting previously unselected package libpython3-stdlib:amd64.
Preparing to unpack .../libpython3-stdlib_3.6.7-1~18.04_amd64.deb ...
Unpacking libpython3-stdlib:amd64 (3.6.7-1~18.04) ...
Setting up python3-minimal (3.6.7-1~18.04) ...
Selecting previously unselected package python3.
(Reading database ... 13859 files and directories currently installed.)
Preparing to unpack .../00-python3_3.6.7-1~18.04_amd64.deb ...
Unpacking python3 (3.6.7-1~18.04) ...
Selecting previously unselected package libmariadb3:amd64.
Preparing to unpack .../01-libmariadb3_3.0.3-1build1_amd64.deb ...
Unpacking libmariadb3:amd64 (3.0.3-1build1) ...
Selecting previously unselected package python3-pkg-resources.
Preparing to unpack .../02-python3-pkg-resources_39.0.1-2_all.deb ...
Unpacking python3-pkg-resources (39.0.1-2) ...
Selecting previously unselected package python3-decorator.
Preparing to unpack .../03-python3-decorator_4.1.2-1_all.deb ...
Unpacking python3-decorator (4.1.2-1) ...
Selecting previously unselected package python3-six.
Preparing to unpack .../04-python3-six_1.11.0-2_all.deb ...
Unpacking python3-six (1.11.0-2) ...
Selecting previously unselected package python3-pbr.
Preparing to unpack .../05-python3-pbr_3.1.1-3ubuntu3_all.deb ...
Unpacking python3-pbr (3.1.1-3ubuntu3) ...
Selecting previously unselected package python3-sqlalchemy.
Preparing to unpack .../06-python3-sqlalchemy_1.1.11+ds1-1ubuntu1_all.deb ...
Unpacking python3-sqlalchemy (1.1.11+ds1-1ubuntu1) ...
Selecting previously unselected package python3-sqlparse.
Preparing to unpack .../07-python3-sqlparse_0.2.4-0.1_all.deb ...
Unpacking python3-sqlparse (0.2.4-0.1) ...
Selecting previously unselected package python3-tempita.
Preparing to unpack .../08-python3-tempita_0.5.2-2_all.deb ...
Unpacking python3-tempita (0.5.2-2) ...
Selecting previously unselected package python3-migrate.
Preparing to unpack .../09-python3-migrate_0.11.0-2_all.deb ...
Unpacking python3-migrate (0.11.0-2) ...
Selecting previously unselected package python3-mysqldb.
Preparing to unpack .../10-python3-mysqldb_1.3.10-1build1_amd64.deb ...
Unpacking python3-mysqldb (1.3.10-1build1) ...
Selecting previously unselected package openvpn-as-bundled-clients.
Preparing to unpack .../11-openvpn-as-bundled-clients_16_all.deb ...
Unpacking openvpn-as-bundled-clients (16) ...
Selecting previously unselected package python3-pyasn1.
Preparing to unpack .../12-python3-pyasn1_0.4.2-3_all.deb ...
Unpacking python3-pyasn1 (0.4.2-3) ...
Selecting previously unselected package python3-ldap3.
Preparing to unpack .../13-python3-ldap3_2.4.1-1_all.deb ...
Unpacking python3-ldap3 (2.4.1-1) ...
Selecting previously unselected package openvpn-as.
Preparing to unpack .../14-openvpn-as_2.9.0-5c5bd120-Ubuntu18_amd64.deb ...
Unpacking openvpn-as (2.9.0-5c5bd120-Ubuntu18) ...
Setting up libmariadb3:amd64 (3.0.3-1build1) ...
Setting up libmpdec2:amd64 (2.4.2-1ubuntu1) ...
Setting up openvpn-as-bundled-clients (16) ...
Setting up libpython3.6-stdlib:amd64 (3.6.9-1~18.04ubuntu1.4) ...
Setting up python3.6 (3.6.9-1~18.04ubuntu1.4) ...
Setting up libpython3-stdlib:amd64 (3.6.7-1~18.04) ...
Setting up python3 (3.6.7-1~18.04) ...
running python rtupdate hooks for python3.6...
running python post-rtupdate hooks for python3.6...
Setting up python3-sqlparse (0.2.4-0.1) ...
Setting up python3-tempita (0.5.2-2) ...
Setting up python3-six (1.11.0-2) ...
Setting up python3-mysqldb (1.3.10-1build1) ...
Setting up python3-pkg-resources (39.0.1-2) ...
Setting up python3-pyasn1 (0.4.2-3) ...
Setting up python3-decorator (4.1.2-1) ...
Setting up python3-pbr (3.1.1-3ubuntu3) ...
update-alternatives: using /usr/bin/python3-pbr to provide /usr/bin/pbr (pbr) in auto mode
Setting up python3-sqlalchemy (1.1.11+ds1-1ubuntu1) ...
Setting up python3-ldap3 (2.4.1-1) ...
Setting up python3-migrate (0.11.0-2) ...
update-alternatives: using /usr/bin/python3-migrate to provide /usr/bin/migrate (migrate) in auto mode
update-alternatives: using /usr/bin/python3-migrate-repository to provide /usr/bin/migrate-repository (migrate-repository) in auto mode
Setting up openvpn-as (2.9.0-5c5bd120-Ubuntu18) ...
Automatic configuration failed, see /usr/local/openvpn_as/init.log
You can configure manually using the /usr/local/openvpn_as/bin/ovpn-init tool.
/var/lib/dpkg/info/openvpn-as.postinst: line 68: systemctl: command not found
Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Stopping openvpn-as now; will start again later after configuring
cat: /var/run/openvpnas.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-openvpn-init: executing...
Detected an existing OpenVPN-AS configuration.
Continuing will delete this configuration and restart from scratch.
Please enter 'DELETE' to delete existing configuration:
          OpenVPN Access Server
          Initial Configuration Tool
------------------------------------------------------
OpenVPN Access Server End User License Agreement (OpenVPN-AS EULA)

    1. Copyright Notice: OpenVPN Access Server License;
       Copyright (c) 2009-2021 OpenVPN Inc. All rights reserved.
       "OpenVPN" is a trademark of OpenVPN Inc.
    2. Redistribution of OpenVPN Access Server binary forms and related documents,
       are permitted provided that redistributions of OpenVPN Access Server binary
       forms and related documents reproduce the above copyright notice as well as
       a complete copy of this EULA.
    3. You agree not to reverse engineer, decompile, disassemble, modify,
       translate, make any attempt to discover the source code of this software,
       or create derivative works from this software.
    4. The OpenVPN Access Server is bundled with other open source software
       components, some of which fall under different licenses. By using OpenVPN
       or any of the bundled components, you agree to be bound by the conditions
       of the license for each respective component. For more information, you can
       find our complete EULA (End-User License Agreement) on our website
       (http://openvpn.net), and a copy of the EULA is also distributed with the
       Access Server in the file /usr/local/openvpn_as/license.txt.
    5. This software is provided "as is" and any expressed or implied warranties,
       including, but not limited to, the implied warranties of merchantability
       and fitness for a particular purpose are disclaimed. In no event shall
       OpenVPN Inc. be liable for any direct, indirect, incidental,
       special, exemplary, or consequential damages (including, but not limited
       to, procurement of substitute goods or services; loss of use, data, or
       profits; or business interruption) however caused and on any theory of
       liability, whether in contract, strict liability, or tort (including
       negligence or otherwise) arising in any way out of the use of this
       software, even if advised of the possibility of such damage.
    6. OpenVPN Inc. is the sole distributor of OpenVPN Access Server
       licenses. This agreement and licenses granted by it may not be assigned,
       sublicensed, or otherwise transferred by licensee without prior written
       consent of OpenVPN Inc. Any licenses violating this provision
       will be subject to revocation and deactivation, and will not be eligible
       for refunds.
    7. Subscription License Key: Entitles you to use this software for the
       duration of term of your subscription up to the concurrent user limit
       specified by your subscription. This license permits you to use the
       software on one or more servers, provided that in no event will the number
       of concurrent VPN connections that all servers may allow exceed the
       concurrent user limit. Upon activation of the first purchased activation
       key for this software, you agree to forego any free licenses or keys that
       were given to you for demonstration purposes, and as such, the free
       licenses will not appear after the activation of a purchased key. You are
       responsible for the timely activation of these licenses on the server or
       servers of your choice.
       Refunds on purchased activation keys are only possible within 30 days of
       purchase of activation key, and then only if the activation key has not
       already been activated on a system. To request a refund, contact us through
       our support ticket system using the account you have used to purchase the
       activation key. Activated subscriptions are nontransferable. Access Server
       Subscription entitles the use of (1) subscription license key on a single
       server or across multiple servers. Once an activated key expires or becomes
       invalid, the concurrency limit on our software product will revert to
       demonstration mode, which allows a maximum of two (2) concurrent users to
       be connected to your server. Prior to your subscription license expiration,
       OpenVPN Inc. will, depending on your purchase selection, either auto-renew
       your subscription, or attempt to remind you to renew your subscription by
       sending periodic email messages to the licensee email address on record.
       You are solely responsible for the timely renewal of your activation key(s)
       prior to their expiration if continued operation is expected after the
       subscription term ends. OpenVPN Inc. will not be responsible for any
       misdirected and/or undeliverable email messages, nor does it have an
       obligation to contact you regarding your subscription term's expiry.
    8. Standard Non-Subscription License Key(s) also called Fixed License Key(s):
       A Purchased Standard Non-Subscription license entitles you to use this
       software for the duration of time denoted on your activation key on any one
       (1) particular device, up to the concurrent user limit specified by your
       license. Multiple activation keys may be activated to achieve a desired
       concurrency limit on this given device. Unless otherwise prearranged with
       OpenVPN Inc., concurrency counts on activation keys are not to be divided
       for use amongst multiple devices. Upon activation of the first purchased
       activation key in this software, you agree to forego any free licenses or
       keys that were given to you for demonstration purposes, and as such, the
       free licenses will not appear after the activation of a purchased key. You
       are responsible for the timely activation of these licenses on your desired
       server of choice. Refunds on purchased activation keys are only possible
       within 30 days of purchase of activation key, and then only if the
       activation key has not already been activated on a system. To request a
       refund, contact us through our support ticket system using the account you
       have used to purchase the activation key.
       Activating a standard Non-Subscription key ties it to the specific
       hardware/software combination that it was activated on, and activated
       activation keys are nontransferable. Substantial software and/or hardware
       changes may invalidate an activated license. In case of substantial
       software and/or hardware changes, caused by for example, but not limited to
       failure and subsequent repair or alterations of (virtualized)
       hardware/software, our software product will automatically attempt to
       contact our online licensing systems to renegotiate the licensing state. On
       any given activation key, you are limited to three (3) automatic
       renegotiations within the activation key lifetime. After these
       renegotiations are exhausted, the activation key is considered invalid, and
       the activation state will be locked to the last valid system configuration
       it was activated on. OpenVPN Inc. reserves the right to grant exceptions to
       this policy for license holders under extenuating circumstances, and such
       exceptions can be requested through a ticket via the OpenVPN Access Server
       ticketing system.
       Once an activated activation key expires or becomes invalid, the
       concurrency limit on our software product will decrease by the number of
       concurrent connections previously granted by the activation key. If all
       purchased activation key(s) have expired, the product will revert to
       demonstration mode, which allows a maximum of two (2) concurrent users to
       be connected to your server. Prior to your license expiration date(s),
       OpenVPN Inc. will attempt to remind you to renew your license(s) by sending
       periodic email messages to the licensee email address on record. You are
       solely responsible for the timely renewal of your activation key(s) prior
       to their expiration if continued operation is expected after the license
       expiration date(s). OpenVPN Inc. will not be responsible for any
       misdirected and/or undeliverable email messages, nor does it have an
       obligation to contact you regarding your expiring activation keys.
    9. Once an activated activation key expires or becomes invalid, the
       concurrency limit on our software product will decrease by the amount of
       concurrent connections previously granted by the activation key. If all of
       your purchased activation key(s) have expired, the product will revert to
       demonstration mode, which allows a maximum of two (2) concurrent users to
       be connected to your server. Prior to your license expiration date(s),
       OpenVPN Inc. will attempt to remind you to renew your license(s) by sending
       periodic email messages to the licensee email address on record. You are
       solely responsible for the timely renewal of your activation key(s) prior
       to their expiration if continued operation is expected after the license
       expiration date(s). OpenVPN Inc. will not be responsible for any
       misdirected and/or undeliverable email messages, nor does it have an
       obligation to contact you regarding your expiring activation keys.
   10. Any valid activation key holder is entitled to use our ticketing system for
       support questions or issues specifically related to the OpenVPN Access
       Server product. To file a ticket, go to our website at https://openvpn.net/
       and sign in using the account that was registered and used to purchase the
       activation key(s). You can then access the support ticket system through
       our website and submit a support ticket. Tickets filed in the ticketing
       system are answered on a best-effort basis. OpenVPN Inc. staff reserve the
       right to limit responses to users of our demo / expired licenses, as well
       as requests that substantively deviate from the OpenVPN Access Server
       product line. Tickets related to the open source version of OpenVPN may
       not be handled here.
   11. Purchasing an activation key does not entitle you to any special rights or
       privileges, except the ones explicitly outlined in this user agreement.
       Unless otherwise arranged prior to your purchase with OpenVPN Inc.,
       software maintenance costs and terms are subject to change after your
       initial purchase without notice. In case of price decreases or special
       promotions, OpenVPN Inc. will not retrospectively apply credits or price
       adjustments toward any licenses that have already been issued. Furthermore,
       no discounts will be given for license maintenance renewals unless this is
       specified in your contract with OpenVPN Inc.

Please enter 'yes' to indicate your agreement [no]:
Once you provide a few initial configuration settings,
OpenVPN Access Server can be configured by accessing
its Admin Web UI using your Web browser.

Will this be the primary Access Server node?
(enter 'no' to configure as a backup or standby node)
> Press ENTER for default [yes]:
Please specify the network interface and IP address to be
used by the Admin Web UI:
(1) all interfaces: 0.0.0.0
(2) eth0: 172.17.0.4
Please enter the option number from the list above (1-2).
> Press Enter for default [1]:
What public/private type/algorithms do you want to use for the OpenVPN CA?

Recommended choices:

rsa       - maximum compatibility
secp384r1 - elliptic curve, higher security than rsa, allows faster connection setup and smaller user profile files
showall   - shows all options including non-recommended algorithms.
> Press ENTER for default [rsa]:Error: This public/private key algorithm is not supported.

What public/private type/algorithms do you want to use for the OpenVPN CA?

Recommended choices:

rsa       - maximum compatibility
secp384r1 - elliptic curve, higher security than rsa, allows faster connection setup and smaller user profile files
showall   - shows all options including non-recommended algorithms.
> Press ENTER for default [rsa]:Error: This public/private key algorithm is not supported.

What public/private type/algorithms do you want to use for the OpenVPN CA?

Recommended choices:

rsa       - maximum compatibility
secp384r1 - elliptic curve, higher security than rsa, allows faster connection setup and smaller user profile files
showall   - shows all options including non-recommended algorithms.
> Press ENTER for default [rsa]:Error: This public/private key algorithm is not supported.

What public/private type/algorithms do you want to use for the OpenVPN CA?

Recommended choices:

rsa       - maximum compatibility
secp384r1 - elliptic curve, higher security than rsa, allows faster connection setup and smaller user profile files
showall   - shows all options including non-recommended algorithms.
> Press ENTER for default [rsa]:Error: This public/private key algorithm is not supported.

What public/private type/algorithms do you want to use for the OpenVPN CA?

Recommended choices:

rsa       - maximum compatibility
secp384r1 - elliptic curve, higher security than rsa, allows faster connection setup and smaller user profile files
showall   - shows all options including non-recommended algorithms.
> Press ENTER for default [rsa]:Error: This public/private key algorithm is not supported.

What public/private type/algorithms do you want to use for the OpenVPN CA?

Recommended choices:

rsa       - maximum compatibility
secp384r1 - elliptic curve, higher security than rsa, allows faster connection setup and smaller user profile files
showall   - shows all options including non-recommended algorithms.
> Press ENTER for default [rsa]:Error: This public/private key algorithm is not supported.

What public/private type/algorithms do you want to use for the OpenVPN CA?

Recommended choices:

rsa       - maximum compatibility
secp384r1 - elliptic curve, higher security than rsa, allows faster connection setup and smaller user profile files
showall   - shows all options including non-recommended algorithms.
> Press ENTER for default [rsa]:Error: This public/private key algorithm is not supported.

What public/private type/algorithms do you want to use for the OpenVPN CA?

Recommended choices:

rsa       - maximum compatibility
secp384r1 - elliptic curve, higher security than rsa, allows faster connection setup and smaller user profile files
showall   - shows all options including non-recommended algorithms.
> Press ENTER for default [rsa]:Error: This public/private key algorithm is not supported.

What public/private type/algorithms do you want to use for the OpenVPN CA?

Recommended choices:

rsa       - maximum compatibility
secp384r1 - elliptic curve, higher security than rsa, allows faster connection setup and smaller user profile files
showall   - shows all options including non-recommended algorithms.
> Press ENTER for default [rsa]:
What key size do you want to use for the certificates?
Key size should be between 2048 and 4096

Traceback (most recent call last):
  File "/usr/local/openvpn_as/bin/_ovpn-init", line 557, in <module>
    OVPN_KEY_ALGORITHM, OVPN_KEY_SIZE = get_cert_algorithms("OpenVPN CA", DEFAULT_KEY_ALGORITHM, DEFAULT_KEY_SIZE)
  File "/usr/local/openvpn_as/bin/_ovpn-init", line 261, in get_cert_algorithms
    user_input = get_raw_input("> Press ENTER for default [ %d ]:" % DEFAULT_KEY_SIZE)
  File "/usr/local/openvpn_as/bin/_ovpn-init", line 78, in get_raw_input
    return input(prompt)
EOFError: EOF when reading a line
> Press ENTER for default [ 2048 ]:Stopping openvpn-as now; will start again later after configuring
cat: /var/run/openvpnas.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
[cont-init.d] 40-openvpn-init: exited 0.
[cont-init.d] 50-interface: executing...
MOD Default {'admin_ui.https.ip_address': None} {'admin_ui.https.ip_address': 'eth0'}
MOD Default {'cs.https.ip_address': None} {'cs.https.ip_address': 'eth0'}
MOD Default {'vpn.daemon.0.listen.ip_address': None} {'vpn.daemon.0.listen.ip_address': 'eth0'}
MOD Default {'vpn.daemon.0.server.ip_address': None} {'vpn.daemon.0.server.ip_address': 'eth0'}
[cont-init.d] 50-interface: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by j0nnymoe** [comment]
Looks like they pushed a new version which has broken our container...again. We will discuss/investigate.

**Comment by aptalca** [comment]
#148
